### ISSUE TITLE
真机运行报错

### ISSUE THREAD

**Issue by newcolor1234** [jwaterwater/uni-nutui#1]
h5浏览器运行是好的
**运行到安卓app，报错**

我是直接使用的示例项目

15:37:25.808 reportJSException >>>> exception function:createInstanceContext, exception:white screen cause create instanceContext failed,check js stack ->Uncaught ReferenceError: Element is not defined
15:37:25.839 at  (app-service.js:21497:22)
15:37:25.870 at  (app-service.js:28517:3)

**Comment by jwaterwater** [comment]
已修复

**Comment by newcolor1234** [comment]
已经不报错了
1. 还有一个问题
菜单中的“Animate 动画/动效”，无法打开，pages中没有配置页面
2. 在NutUI的官方实例 https://nutui.jd.com/#/zh-CN/component/button 中，还有很多示例没有展示，是不是不兼容？
