### ISSUE TITLE
Swiper在微信小程序中使用时报错

### ISSUE THREAD

**Issue by jincandev** [jwaterwater/uni-nutui#16]
![image](https://user-images.githubusercontent.com/7412888/222971670-ee599db9-fc57-4691-8c0a-477b2f7bcafe.png)
应该是Swiper组件里面的`requestAnimationFrame`方法在微信小程序中不受支持
![image](https://user-images.githubusercontent.com/7412888/222971750-99d0d36b-6332-4d96-8912-c9239a32fe40.png)

**Comment by jwaterwater** [comment]
看下readme, swiper未作支持, 使用uniapp的swiper组件替代
