### ISSUE TITLE
小程序中使用Divider 分割线无法自定义颜色

### ISSUE THREAD

**Issue by toolvip** [jwaterwater/uni-nutui#18]
`<template>
  <nut-divider :style="{ color: '#1989fa', borderColor: '#1989fa', padding: '0 16px' }">文本</nut-divider>
</template>`
color不起作用，还是默认的颜色

**Comment by jwaterwater** [comment]
uniapp 环境  组件style属性是无效的, 无法绑定到,  你需要这个功能的话可以提一个pr,  用props实现一下样式

**Comment by toolvip** [comment]
> uniapp 环境 组件样式属性是无效的， 无法绑定到， 你需要这个功能的话可以提一个PR， 用props实现一下样式

好的，谢谢
