### ISSUE TITLE
sticky 好像用不了 其他都能用

### ISSUE THREAD

**Issue by chenshuhao** [jwaterwater/uni-nutui#4]
Component is not found in path "uni_modules/sky-nutui/components/sky-nutui/packages/__VUE/sticky/index" (using by "pages/template/index")(env: macOS,mp,1.06.2209070; lib: 2.26.1)

**Comment by jwaterwater** [comment]
sticky 未作兼容,  参考下方演示, 演示内包含的组件都是兼容了的
