### ISSUE TITLE
使用tab组件时候 cli的状态下 icon报错

### ISSUE THREAD

**Issue by leftScience** [jwaterwater/uni-nutui#7]
<img width="1415" alt="image" src="https://user-images.githubusercontent.com/47803644/201461241-b4bc2254-09d0-4a98-8875-b804661bea02.png">
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/47803644/201461255-ab3ef66b-8ef7-4ac0-9bf6-ab19a55dc582.png">
<img width="531" alt="image" src="https://user-images.githubusercontent.com/47803644/201461264-96137524-18bd-4263-9b21-5e1be9f2638f.png">

**Comment by jwaterwater** [comment]
1 小程序还是h5
2 是否配置easycom

**Comment by leftScience** [comment]
1.h5 2.配置了



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年11月12日 15:54 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [jwaterwater/uni-nutui] 使用tab组件时候 cli的状态下 icon报错 (Issue #7) |

1 小程序还是h5
2 是否配置easycom

**Comment by jwaterwater** [comment]
测试没发现  你自己查源码找找原因吧
